services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metacatalog
    ports:
      - 54322:5432
    volumes:
      - ./data/dev/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 15s
      timeout: 1s
      retries: 5
      start_period: 2s
  
  api:
    build: .
    environment:
      METACATALOG_URI: postgresql://postgres:postgres@db:5432/metacatalog
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8008:8000
    volumes:
      # for development, link the source code directly
      - ./metacatalog-api:/app/metacatalog-api
      - ./src:/app
    # only for development
    command: "python creative_uploader.py --reload=True"
    #command: "python creative_uploader.py"